### ISSUE TITLE
Invalid Camera Slug - Docs addition?

### ISSUE THREAD

**Issue by bailboy91** [roflcoopter/viseron#361]
After your round of updates recently i realized no snapshots where being pushed to homeassistant.  Digging into the logs I saw that it failed to start due to an invalid camera slug.  

Error:
`[2022-08-29 20:58:56] [ERROR   ] [viseron.helpers.validators] - invalid slug viseron-front (try viseron_front)`

 After some testing it appears that the background subtractor and object detector sections cannot have a `-` in the name for the camera definitions.   
Valid:
```background_subtractor:
  motion_detector:
    cameras:
      viseron_front:
```
Invalid:
```background_subtractor:
  motion_detector:
    cameras:
      viseron_front:
```
Simply changing all to match the suggestion from the error worked and I even have a live feed for the first time ever working through the web interface.  

I guess not so much an error but something to add to the docs?

**Comment by roflcoopter** [comment]
Definitely!

I have changed how the camera identifier is validated, but i have not gotten to ffmpeg/gstreamer yet so they still allow the old values.

When I am done with the docs for all components the validation will be uniform across all of them.
Closing this for now since its in the works already. Thanks for the report.
