### ISSUE TITLE
CompreFace - only one 'unknown' face is saved

### ISSUE THREAD

**Issue by gofaster** [roflcoopter/viseron#436]
If more than one unknown (below similarity threshold) face is present, only one is saved.

CompreFace returns a list of subjects ordered by similarity.
[https://github.com/exadel-inc/CompreFace/blob/master/docs/Rest-API-description.md#recognize-faces-from-a-given-image](url)

Appears the only the first element is saved?
https://github.com/roflcoopter/viseron/blob/55d8380628aa66f5651bc2a6401264bbc96a8a39/viseron/components/compreface/face_recognition.py#L108

**Comment by roflcoopter** [comment]
You are correct, will fix

**Comment by roflcoopter** [comment]
Actually when looking at it again, are you sure about that?

I am looping over all the results here:
https://github.com/roflcoopter/viseron/blob/55d8380628aa66f5651bc2a6401264bbc96a8a39/viseron/components/compreface/face_recognition.py#L107

Which has one entry for each found face.

Then i grab the one with the highest accuracy here:
https://github.com/roflcoopter/viseron/blob/55d8380628aa66f5651bc2a6401264bbc96a8a39/viseron/components/compreface/face_recognition.py#L108

If i would loop over all the subjects it would process `number of faces in the image * number of trained subjects` which is not correct

I ran a test on an image with tho faces and this is the result:
```json
{
   "result":[
      {
         "age":{
            "probability":0.4827486276626587,
            "high":53,
            "low":48
         },
         "gender":{
            "probability":1,
            "value":"male"
         },
         "box":{
            "probability":0.9997,
            "x_max":178,
            "y_max":139,
            "x_min":83,
            "y_min":34
         },
         "subjects":[
            {
               "subject":"rebecca",
               "similarity":0.07799
            }
         ],
         "landmarks":[
            [
               107,
               80
            ],
            [
               129,
               71
            ],
            [
               115,
               92
            ],
            [
               119,
               112
            ],
            [
               138,
               105
            ]
         ]
      },
      {
         "age":{
            "probability":0.7517662048339844,
            "high":43,
            "low":38
         },
         "gender":{
            "probability":0.974775493144989,
            "value":"male"
         },
         "box":{
            "probability":0.99744,
            "x_max":95,
            "y_max":113,
            "x_min":8,
            "y_min":23
         },
         "subjects":[
            {
               "subject":"jesper",
               "similarity":0.33593
            }
         ],
         "landmarks":[
            [
               36,
               63
            ],
            [
               62,
               56
            ],
            [
               49,
               73
            ],
            [
               43,
               92
            ],
            [
               68,
               86
            ]
         ]
      }
   ]
}
```

As you can see the results list has two entries, one for each face, which both would be saved as unknown faces since the similarity is low

**Comment by gofaster** [comment]
Thanks for digging into it.  
In my case, when the object detector `sees` 2 (or more) persons, Compreface only saves one.  
I will have to simplify my config and do more controlled testing.
