### ISSUE TITLE
Developer Docs

### ISSUE THREAD

**Issue by jMyles** [roflcoopter/viseron#480]
Hey this is a great project.

I'm interested in helping out.

Are there developer docs?

Where to jump in?

**Comment by roflcoopter** [comment]
Awesome to hear!

Sadly I have not gotten to the developer docs yet, there is some information in the Contributing section of the docs, but it does not explain the inner workings of Viseron.
I should make it a priority to fix some good developer docs to attract more devs.

Is there any part that you are particularly interested in? Otherwise just looking at any of the open issues or feature requests is a good idea.

We can discuss as you go along until I can sort out the docs.

**Comment by jMyles** [comment]
First question:

How can I run a version with my own changes?

Is there a python module I can evaluate and run in a debugger for the purposes of working on it?

I'd love to be able to hit a breakpoint in realtime, from my own setup.

**Comment by roflcoopter** [comment]
When I develop I build the container locally using this command: `docker-compose --file ./azure-pipelines/docker-compose-build.yaml --env ./azure-pipelines/.env build amd64-viseron`

I have not used a debugger but it should be possible to set it up using vscode
https://code.visualstudio.com/docs/containers/debug-python

Making a devcontainer would probably be a good idea

**Comment by roflcoopter** [comment]
The devdocs are now in progress and can be found here: https://dev--viseron.netlify.app/docs/developers
