### ISSUE TITLE
Some screen shots and demo if possible

### ISSUE THREAD

**Issue by Mohammad699** [roflcoopter/viseron#779]
Hi,
Most of us just want to see the software or try it before installing, so if possible can you make a demo website and post some screens here.
Thank you

**Comment by roflcoopter** [comment]
Hello! Understandable, will make sure to add more screenshots to the docs.
Not sure how to solve the demo part, I am reluctant to host it myself due to security concerns, and using a VPS would introduce a monthly cost which i am also not a fan of since i do not earn much money from Viseron atm.
Will need to think about how to solve that

**Comment by Mohammad699** [comment]
Screen shots will be enough for now.
For the demo maybe you find some hosting providers to sponser the project with a VPS or something like that.
Thank you for your efforts and good work.

**Comment by roflcoopter** [comment]
This took longer than i would have liked but with the 3.0.0 release, there are now screenshots in the docs: https://viseron.netlify.app/docs/documentation#screenshots
